/**
 * Browser-safe cryptography for Quantix wallet.
 * Uses @noble/post-quantum for ML-DSA-87 and @noble/hashes for SHA-256.
 * Does NOT use node:crypto.
 */
import { ml_dsa87 } from "@noble/post-quantum/ml-dsa.js";
import { sha256 } from "@noble/hashes/sha2.js";

const ML_DSA87_LENGTHS = ml_dsa87.lengths;

// ── Types ────────────────────────────────────────────────────────────────────

export interface KeyPair {
  publicKey: Uint8Array;
  privateKey: Uint8Array;
}

export interface WalletFile {
  version: "quantix-key/v1";
  address: string;
  publicKey: string; // hex
  privateKey: string; // hex
  seed?: string; // hex, optional
  createdAt: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function toHex(b: Uint8Array): string {
  return Array.from(b)
    .map((x) => x.toString(16).padStart(2, "0"))
    .join("");
}

function fromHex(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (!/^[0-9a-fA-F]*$/.test(clean)) throw new Error("Invalid hex content");
  if (clean.length % 2 !== 0) throw new Error("Invalid hex length");
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function validateKeyPairLengths(publicKey: Uint8Array, privateKey: Uint8Array): void {
  if (publicKey.length !== ML_DSA87_LENGTHS.publicKey) {
    throw new Error(
      `Incompatible wallet public key length: expected ${ML_DSA87_LENGTHS.publicKey} bytes, got ${publicKey.length}. ` +
      "This wallet file is not an ML-DSA-87 raw key file.",
    );
  }
  if (privateKey.length !== ML_DSA87_LENGTHS.secretKey) {
    throw new Error(
      `Incompatible wallet private key length: expected ${ML_DSA87_LENGTHS.secretKey} bytes, got ${privateKey.length}. ` +
      "This wallet file is likely from an older/incompatible format. Please import a key generated by this wallet.",
    );
  }
}

// ── Address derivation ───────────────────────────────────────────────────────

/** Derive a Quantix address from a public key. Format: qtx1 + first 38 hex chars of sha256(pubkey). */
export function deriveAddress(publicKey: Uint8Array): string {
  // Must match node/SDK: sha256 over UTF-8 bytes of public-key hex string.
  const publicKeyHex = toHex(publicKey);
  const hash = sha256(new TextEncoder().encode(publicKeyHex));
  return "qtx1" + toHex(hash).slice(0, 38);
}

// ── Key generation ───────────────────────────────────────────────────────────

/** Generate a fresh ML-DSA-87 key pair. */
export function generateKeyPair(): KeyPair & { address: string } {
  const { publicKey, secretKey } = ml_dsa87.keygen();
  return {
    publicKey,
    privateKey: secretKey,
    address: deriveAddress(publicKey),
  };
}

// ── Signing ──────────────────────────────────────────────────────────────────

/**
 * Sign a payload string (the canonical JSON from transactionSigningPayload).
 * Returns hex-encoded signature.
 */
export function signPayload(privateKey: Uint8Array, payload: string): string {
  if (privateKey.length !== ML_DSA87_LENGTHS.secretKey) {
    throw new Error(
      `Cannot sign with this private key: expected ${ML_DSA87_LENGTHS.secretKey} bytes, got ${privateKey.length}. ` +
      "Use a valid ML-DSA-87 wallet file.",
    );
  }
  const data = new TextEncoder().encode(payload);
  const sig = ml_dsa87.sign(data, privateKey);
  return toHex(sig);
}

// ── Wallet file ──────────────────────────────────────────────────────────────

export function walletToJson(kp: KeyPair): WalletFile {
  const address = deriveAddress(kp.publicKey);
  return {
    version: "quantix-key/v1",
    address,
    publicKey: toHex(kp.publicKey),
    privateKey: toHex(kp.privateKey),
    createdAt: new Date().toISOString(),
  };
}

export function parseWalletFile(json: unknown): WalletFile {
  if (typeof json !== "object" || json === null) throw new Error("Invalid wallet file");
  const w = json as Record<string, unknown>;
  if (w.version !== "quantix-key/v1") throw new Error("Unsupported wallet version");
  if (typeof w.address !== "string") throw new Error("Missing address");
  if (typeof w.publicKey !== "string") throw new Error("Missing publicKey");
  if (typeof w.privateKey !== "string") throw new Error("Missing privateKey");

  const publicKey = fromHex(w.publicKey);
  const privateKey = fromHex(w.privateKey);
  validateKeyPairLengths(publicKey, privateKey);

  if (!w.address.startsWith("qtx1") || w.address.length !== 42) {
    throw new Error("Invalid address format in wallet file");
  }

  const derived = deriveAddress(publicKey);
  if (derived !== w.address) {
    throw new Error("Wallet file address does not match public key");
  }

  return {
    version: "quantix-key/v1",
    address: w.address,
    publicKey: w.publicKey,
    privateKey: w.privateKey,
    seed: typeof w.seed === "string" ? w.seed : undefined,
    createdAt: typeof w.createdAt === "string" ? w.createdAt : new Date().toISOString(),
  };
}

export function walletFileToKeyPair(wf: WalletFile): KeyPair {
  const publicKey = fromHex(wf.publicKey);
  const privateKey = fromHex(wf.privateKey);
  validateKeyPairLengths(publicKey, privateKey);
  return { publicKey, privateKey };
}
